import type { StaffMember } from "@/types/staff";

const d = (daysOffset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString();
};

export const MOCK_STAFF: StaffMember[] = [
  {
    id: "s-01",
    name: "Carlos Mendoza",
    email: "carlos.mendoza@foodify.mx",
    phone: "33 1234 5678",
    role: "restaurant_admin",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-120),
    lastLogin: d(-1),
    avatarInitials: "CM",
  },
  {
    id: "s-02",
    name: "María González",
    email: "maria.gonzalez@foodify.mx",
    phone: "33 2345 6789",
    role: "manager",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-90),
    lastLogin: d(-2),
    avatarInitials: "MG",
  },
  {
    id: "s-03",
    name: "Luis Hernández",
    email: "luis.hernandez@foodify.mx",
    phone: "33 3456 7890",
    role: "waiter",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-60),
    lastLogin: d(0),
    avatarInitials: "LH",
  },
  {
    id: "s-04",
    name: "Ana Martínez",
    email: "ana.martinez@foodify.mx",
    phone: "33 4567 8901",
    role: "waiter",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-45),
    lastLogin: d(-3),
    avatarInitials: "AM",
  },
  {
    id: "s-05",
    name: "Roberto Díaz",
    email: "roberto.diaz@foodify.mx",
    phone: "33 5678 9012",
    role: "chef",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-80),
    lastLogin: d(0),
    avatarInitials: "RD",
  },
  {
    id: "s-06",
    name: "Sandra López",
    email: "sandra.lopez@foodify.mx",
    phone: "33 6789 0123",
    role: "chef",
    status: "inactive",
    branch: "Centro Histórico",
    createdAt: d(-100),
    lastLogin: d(-15),
    avatarInitials: "SL",
  },
  {
    id: "s-07",
    name: "Pedro Ramírez",
    email: "pedro.ramirez@foodify.mx",
    phone: "33 7890 1234",
    role: "cashier",
    status: "active",
    branch: "Centro Histórico",
    createdAt: d(-30),
    lastLogin: d(-1),
    avatarInitials: "PR",
  },
  {
    id: "s-08",
    name: "Daniela Torres",
    email: "daniela.torres@foodify.mx",
    phone: "33 8901 2345",
    role: "waiter",
    status: "suspended",
    branch: "Centro Histórico",
    createdAt: d(-50),
    lastLogin: d(-20),
    avatarInitials: "DT",
  },
];
